version: '3'

services:

  db_writer:
    env_file:
      - .env
      - .env.override
    build:
      context: .
      dockerfile: docker/db_writer/Dockerfile
    volumes:
      - ./db_writer:/db_writer
      - ./db:/db
    networks:
      - notification
    ports:
      - '$DB_WRITER_PORT:$DB_WRITER_PORT'
    command: 'bash -c "gunicorn source:make_app -w $DB_WRITER_WORKERS --bind 0.0.0.0:$DB_WRITER_PORT --worker-class aiohttp.GunicornUVLoopWebWorker --reload --log-level debug"'

  email_sender:
    env_file:
      - .env
      - .env.override
    build:
      context: .
      dockerfile: docker/email_sender/Dockerfile
    volumes:
      - ./email_sender:/email_sender
    networks:
      - notification
    ports:
      - '$EMAIL_SENDER_PORT:$EMAIL_SENDER_PORT'
    command: 'bash -c "gunicorn source:make_app -w 1 --bind 0.0.0.0:$EMAIL_SENDER_PORT --worker-class aiohttp.GunicornUVLoopWebWorker --reload --log-level debug"'

networks:
  notification:
    driver: bridge
