version: '3'

services:

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    networks:
      - notification
    ports:
      - '$MONGO_PORT:$MONGO_PORT'

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - ./backend:/backend
    networks:
      - notification
    ports:
      - '$BACKEND_PORT:$BACKEND_PORT'
    command: 'wait-for-it.sh "mongo:${MONGO_PORT}" --
              bash -c "gunicorn app:make_app -w $BACKEND_WORKERS --bind 0.0.0.0:$BACKEND_PORT --worker-class aiohttp.GunicornUVLoopWebWorker --reload --log-level debug"'

  notifier:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/notifier/Dockerfile
    volumes:
      - ./notifier:/notifier
    networks:
      - notification
    ports:
      - '$NOTIFIER_PORT:$NOTIFIER_PORT'
    command: 'bash -c "gunicorn app:make_app -w 1 --bind 0.0.0.0:$NOTIFIER_PORT --worker-class aiohttp.GunicornUVLoopWebWorker --reload --log-level debug"'

networks:
  notification:
    driver: bridge
